<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="assets/styles/styles.css">
    <title>Smart Money Management - Welcome!</title>
</head>

<body>
<div class="navbar navbar-dark bg-dark fixed-top p-0">
    <a class="navbar-nav">
        <form class="form-inline btn-block">
			<button class="btn btn-success" type="button" onclick="window.location.href='/'">Home</button>
            <button class="btn btn-success" type="button" onclick="window.location.href='/add-expense'">Add expense</button>
            <button class="btn btn-success" type="button" onclick="window.location.href='/add-income'">Add income</button>
            <button class="btn btn-success" type="button" onclick="window.location.href='/charts'">Charts</button>
            <button class="btn btn-success" type="button" onclick="window.location.href='/summary'">Summary</button>
        </form>
    </a>
    <a class="navbar ml-md-auto">
        <button class="btn btn-success" type="button">Settings</button>
    </a>
    <a class="navbar-brand" href="#test" aria-label="Contact us">
        <img src="assets/images/RoadRunners_Logo_50px.gif" class="d-inline-block align-middle" alt="Logo">
    </a>
</div>
